spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/batch_process?createDatabaseIfNotExist=true&useSSL=false
    password: ''
  batch:
    jdbc:
      initialize-schema: always
      schema: classpath:/org/springframework/batch/core/schema-mysql.sql
    job:
      enabled: 'true'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
inputFile: data.csv
